### ISSUE TITLE
получение данных должно быть в componentDidMount

### ISSUE THREAD

**Issue by vladimirperepelytsia** [ValkoBob/Project-for-Onix#3]
https://github.com/ValkoBob/Project-for-Onix/blob/82eac93e843e1aefd814186601a164c4906dc90f/src/components/forecast/index.js#L27

**Comment by ValkoBob** [comment]
Перереробив дане зауваження
https://github.com/ValkoBob/Project-for-Onix/blob/2df3d9944dc88d886e3d864a8638c78dc3507bc1/src/components/forecast/index.js#L23
